
name: 'jaffle_shop'
version: '0.1'
config-version: 2
profile: 'jaffle_shop'
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

seeds:
  jaffle_shop: # you must include the project name
    raw_locations:
      +column_types:
        opened_at: varchar(20)

models:
  jaffle_shop:
      materialized: table
      staging:
        materialized: view
        tags: ["staging", "hourly"]

# comment 2